buildscript {
    repositories {
        jcenter()
        maven { url = "http://files.minecraftforge.net/maven" }
    }
    dependencies {
        classpath 'net.minecraftforge.gradle:ForgeGradle:2.3-SNAPSHOT'
    }
}
apply plugin: 'net.minecraftforge.gradle.forge'
apply plugin: 'maven-publish'

version = "1.0.0"
group = "com.umorist.mods"
archivesBaseName = "mods-combined"

sourceCompatibility = targetCompatibility = '1.8'
compileJava {
    sourceCompatibility = targetCompatibility = '1.8'
}

minecraft {
    version = "1.12.2-14.23.5.2860"
    runDir = "run"
    mappings = "snapshot_20171003"
    useDepAts = true
}

dependencies {
}

processResources {
    inputs.property "version", project.version
    inputs.property "mcversion", minecraft.version
    from(sourceSets.main.resources.srcDirs) {
        include 'mcmod.info'
        expand 'version':project.version, 'mcversion':minecraft.version
    }
    from(sourceSets.main.resources.srcDirs) {
        exclude 'mcmod.info'
    }
}

jar {
    manifest {
        attributes(
                "Specification-Title": "mods",
                "Specification-Vendor": "umorist",
                "Specification-Version": "1",
                "Implementation-Title": "mods",
                "Implementation-Version": "${version}",
                "Implementation-Vendor": "umorist",
                "Implementation-Timestamp": new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        )
    }
}

repositories {
    mavenCentral()
}
